public enum SoundEffectType
{
	RobotDamage,
	PlayerRobotIdle,
	PlayerRobotMovement,
	PlayerRobotShoot,
	TileDestructionByPlayerRobotBullet,
	PlayerRobotBulletHit,
	PlayerRobotExplosion,
	PlayerRobotLifeGain,
	PlayerRobotSliding,
	EnemyRobotExplosion,
	NukeExplosion,
	BonusSpawn,
	BonusCollect,
	GamePause,
	PointsCount,
	BonusPointsAward
}